server {
    listen 3000;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: todas las rutas devuelven index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al BFF (API Gateway en prod, BFF local en dev)
    location /v1/ {
        proxy_pass http://bff:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /v2/ {
        proxy_pass http://bff:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
