spring:
  application:
    name: ms-catalogo

server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mesatech}
    username: ${DB_USER:mesatech}
    password: ${DB_PASSWORD:mesatech_dev}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

logging:
  level:
    root: INFO
    com.mesatech: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
